version: '3.7'

services:
  payara:
    build: ./docker/images/payara
    image: payara/server-full
    container_name: stackoverflow
    ports:
     - "8080:8080"
     - "4848:4848"
     - "8181:8181"
