version: '3.7'

# https://medium.com/@hantsy/put-your-jakarta-ee-8-applications-to-production-77756d1967bf

services:
  openliberty:
    build: .
    image: openliberty/stack
    container_name: stackoverflow
    ports:
      - "9080:9080"
      - "9443:9443" # HTTPS listener
  
  mysql:
    image: mysql:latest
    ports:
      - 9906:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: AMT-test