version: '3.7'

# https://medium.com/@hantsy/put-your-jakarta-ee-8-applications-to-production-77756d1967bf

services:
  openliberty:
    build: .
    image: openliberty/stack
    container_name: stackoverflow
    ports:
      - "9080:9080"
      - "9443:9443" # HTTPS listener
