version: "3.7"

# https://medium.com/@hantsy/put-your-jakarta-ee-8-applications-to-production-77756d1967bf

services:
  db:
    image: mysql:8.0.18
    container_name: stack_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9906:3306
    volumes:
      - ./init/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: AMT-db
      MYSQL_USER: stackusr
      MYSQL_PASSWORD: stackpwd
      TZ: "Europe/Zurich"
  web:
    image: ghcr.io/pabloheigvd/flow
    container_name: stackoverflow
    ports:
      - "9080:9080"
      - "9443:9443" # HTTPS listener
    volumes:
      - ../src/main/liberty/config/server.env:/config/server.env
    depends_on:
      - db

