name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: General informations
        run: |
          echo "$GITHUB_WORKFLOW workflow is running"
          echo "Hi $GITHUB_ACTOR !"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # copie bete de la vidéo https://youtu.be/jrTIZBMmqhI?t=630
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven build
        run: mvn clean package

      # Install test environnement functions but not E2E tests
      #- name: Install test environnement
      #  # NOTE: this pins the action to a specific commit sha for security
      #  # reasons but you can also use a version tag if desired. For example:
      #  # ianwalter/puppeteer-container@v4.0.0
      #  uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
      #  with:
      #    args: pnpm i
      #
      #- name: E2E tests
      #  uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
      #  with:
      #    args: pnpm t

      - name: Build Docker image and push it to ghcr
        run: |
          echo ${{ secrets.PUSH_IMAGES_TO_GHCR_SECRET }} | docker login ghcr.io -u pabloheigvd --password-stdin
          docker build -t pabloheigvd/flow .
          docker tag pabloheigvd/flow ghcr.io/pabloheigvd/flow
          docker push ghcr.io/pabloheigvd/flow
